%% EHY_pp_wl General EHY postprocessing script
function EHY_pp_wl(varargin)

warning (sprintf(['Warning: The functionality of this function is part of EHY_pp \n'                 ...
                  '         EHY_pp allows for plotting other variables than water level \n'          ...
                  '         You can add, for instance, varName = salinity to the chapter General \n' ...
                  '         If you dont specify varName, wl (water level) is assumed so \n'          ...
                  '         existing ini files should work. \n'                                      ...
                  '         Please use EHY_pp from now on.'                                        ]));                  

EHY_pp(varargin{1});
              
