function stations = getHistoricStations(obj)
%getHistoricStations(obj)
%
%     Input:
%   
%     Output:
%       stations = (stations)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/historicstations/wsdl', ...
    'getHistoricStations', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
stations = parseSoapResponse(response);
