function t_disp
%T_DISP    displays table of all 146 t_tide components with various units
%
%See also: T_TIDE, T_GETCONSTS

   [const,sat,shallow]=t_getconsts;
   
   disp('t_tide constituens table:')
      disp([pad('#'      ,' ', -3),'  ',...
            pad('name'   ,' ', -6),'  ',...
            pad('deg/hr' ,' ',-12),'  ',...
            pad('hr/cyc' ,' ',-12),'  ',...
            pad('cyc/hr' ,' ',-12),'  ',...
            pad('cyc/day',' ',-12)]);
   
      disp([pad('-','-', -3),'  '...
            pad('-','-', -6),'  ',...
            pad('-','-',-12),'  ',...
            pad('-','-',-12),'  ',...
            pad('-','-',-12),'  ',...
            pad('-','-',-12)]);
   for icomp=1:size(const.name,1)
   
      disp([pad(num2str(           icomp,3      ),' ', -3),'  ',...
            pad(        const.name(icomp,:)      ,' ', -6),'  ',...
            pad(num2str(const.freq(icomp,:)*360 ),' ',-12),'  ',...
            pad(num2str(const.freq(icomp,:)^(-1)),' ',-12),'  ',...
            pad(num2str(const.freq(icomp,:)     ),' ',-12),'  ',...
            pad(num2str(const.freq(icomp,:)*24  ),' ',-12),'  ',...
            ]);
   
   end
   
%% EOF   