function writeParams(mdl,dr)

fid=fopen([dr 'params.txt'],'wt');

fprintf(fid,'%s\n','grid input');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n',['nx       = ' num2str(mdl.nx)]);
fprintf(fid,'%s\n','ny       = 2');
fprintf(fid,'%s\n',['dx       = ' num2str(mdl.dx)]);
fprintf(fid,'%s\n',['dy       = ' num2str(mdl.dy)]);
fprintf(fid,'%s\n',['xori     = ' num2str(mdl.xori)]);
fprintf(fid,'%s\n',['yori     = ' num2str(mdl.yori)]);
fprintf(fid,'%s\n',['alfa     = ' num2str(mdl.alpha)]);
fprintf(fid,'%s\n',['depfile  = ' mdl.depfile]);
fprintf(fid,'%s\n','vardx    = 0');
fprintf(fid,'%s\n','posdwn   = -1');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','wave input');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','break    = 3');
fprintf(fid,'%s\n','hmin     = 0.20');
fprintf(fid,'%s\n','gamma    = 0.50');
fprintf(fid,'%s\n','alpha    = 1.');
fprintf(fid,'%s\n','delta    = 0.0');
fprintf(fid,'%s\n','n        = 10');
fprintf(fid,'%s\n','rho      = 1025.0');
fprintf(fid,'%s\n','g        = 9.81');
fprintf(fid,'%s\n','thetamin = -70');
fprintf(fid,'%s\n','thetamax = 70');
fprintf(fid,'%s\n','dtheta   = 20');
fprintf(fid,'%s\n','wci      = 0');
fprintf(fid,'%s\n','instat   = 5');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','nuh      = 0.1');
fprintf(fid,'%s\n','nuhfac   = 1');
fprintf(fid,'%s\n','roller   = 1');
fprintf(fid,'%s\n','beta     = 0.1');
fprintf(fid,'%s\n','bcfile   = t.t');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','flow input');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','zs0file  = tidedata.dat');
fprintf(fid,'%s\n','tideloc  = 2');
fprintf(fid,'%s\n','tidelen  = TIDELENKEY');
fprintf(fid,'%s\n','paulrevere = 1');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','zs0      = 0');
fprintf(fid,'%s\n','C        = 65.');
fprintf(fid,'%s\n','eps      = 0.01');
fprintf(fid,'%s\n','umin     = 0.0');
fprintf(fid,'%s\n','tstart   = 0');
fprintf(fid,'%s\n','tintg    = DTMAPKEY');
fprintf(fid,'%s\n','tintp    = DTHISKEY');
fprintf(fid,'%s\n','tintm    = DTMAPKEY');
fprintf(fid,'%s\n','tstop    = TSTOPKEY');
fprintf(fid,'%s\n','CFL      = 0.9');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','sed input');
fprintf(fid,'%s\n','');
fprintf(fid,'%s\n','A        = 0.002');
fprintf(fid,'%s\n','dico	 = 1.0');
fprintf(fid,'%s\n','D50      = 0.000250');
fprintf(fid,'%s\n','D90      = 0.000375');
fprintf(fid,'%s\n','rhos     = 2650');
fprintf(fid,'%s\n','morfac   = 10');
fprintf(fid,'%s\n','morstart = 3600');
fprintf(fid,'%s\n','por      = 0.4');
fprintf(fid,'%s\n','dryslp   = 1.0');
fprintf(fid,'%s\n','wetslp   = 0.15');
fprintf(fid,'%s\n','hswitch  = 0.1');

fclose(fid);
