function sp2 = xb_swan_struct()
%XB_SWAN_STRUCT  Create empty SWAN structure
%
%   Create empty SWAN structure
%
%   Syntax:
%   sp2 = xb_swan_struct()
%
%   Input:
%   none
%
%   Output:
%   sp2       = Empty SWAN structure
%
%   Example
%   sp2 = xb_swan_struct
%
%   See also xb_swan_read, xb_swan_write

%% Copyright notice
%   --------------------------------------------------------------------
%   Copyright (C) 2011 Deltares
%       Bas Hoonhout
%
%       bas.hoonhout@deltares.nl	
%
%       Rotterdamseweg 185
%       2629HD Delft
%
%   This library is free software: you can redistribute it and/or
%   modify it under the terms of the GNU Lesser General Public
%   License as published by the Free Software Foundation, either
%   version 2.1 of the License, or (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%   Lesser General Public License for more details.
%
%   You should have received a copy of the GNU Lesser General Public
%   License along with this library. If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

% This tool is part of <a href="http://OpenEarth.nl">OpenEarthTools</a>.
% OpenEarthTools is an online collaboration to share and manage data and 
% programming tools in an open source, version controlled environment.
% Sign up to recieve regular updates of this function, and to contribute 
% your own tools.

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>
% Created: 14 Feb 2011
% Created with Matlab version: 7.9.0.529 (R2009b)

% $Id: xb_swan_struct.m 8278 2013-03-05 17:55:59Z hoonhout $
% $Date: 2013-03-06 01:55:59 +0800 (Wed, 06 Mar 2013) $
% $Author: hoonhout $
% $Revision: 8278 $
% $HeadURL: https://svn.oss.deltares.nl/repos/openearthtools/trunk/matlab/applications/xbeach/xb_nesting/xb_swan/xb_swan_struct.m $
% $Keywords: $

%% create empty SP2 struct

sp2 = struct( ...
    'has_time',false, ...
    'run',1, ...
    'time',struct( ...
        'nr',1, ...
        'data',[], ...
        'type','yyymmdd.hhmmss' ...
    ), ...
    'location',struct( ...
        'nr',0, ...
        'data',[], ...
        'type','' ...
    ), ...
    'frequency',struct( ...
        'nr',0, ...
        'data',[], ...
        'type','' ...
    ), ...
    'direction',struct( ...
        'nr',0, ...
        'data',[], ...
        'type','' ...
    ), ...
    'spectrum',struct( ...
        'nr',0, ...
        'data',[], ...
        'type','', ...
        'factor',[], ...
        'unit','', ...
        'exception',0 ...
    ) ...
);