function data = getVisibility(obj,stationId,beginDate,endDate)
%getVisibility(obj,stationId,beginDate,endDate)
%
%     Input:
%       stationId = (string)
%       beginDate = (string)
%       endDate = (string)
%   
%     Output:
%       data = (ArrayOfData)

% Build up the argument lists.
values = { ...
   stationId, ...
   beginDate, ...
   endDate, ...
   };
names = { ...
   'stationId', ...
   'beginDate', ...
   'endDate', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/visibility/wsdl', ...
    'getVisibility', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
data = parseSoapResponse(response);
