function getESD_DataFormatResult = getESD_DataFormat(obj,tblCodeID_Dataset,tblCodeID_Param,tblCodeID_Matrx,intYear,tblCodeID_Taxa,tblCodeID_Area,page)
%getESD_DataFormat(obj,tblCodeID_Dataset,tblCodeID_Param,tblCodeID_Matrx,intYear,tblCodeID_Taxa,tblCodeID_Area,page)
%
%   Get the data by pages
%   
%     Input:
%       tblCodeID_Dataset = (string)
%       tblCodeID_Param = (string)
%       tblCodeID_Matrx = (string)
%       intYear = (string)
%       tblCodeID_Taxa = (string)
%       tblCodeID_Area = (string)
%       page = (double)
%   
%     Output:
%       getESD_DataFormatResult = (ArrayOfICESStatisticalRectanglesGrid)

% Build up the argument lists.
values = { ...
   tblCodeID_Dataset, ...
   tblCodeID_Param, ...
   tblCodeID_Matrx, ...
   intYear, ...
   tblCodeID_Taxa, ...
   tblCodeID_Area, ...
   page, ...
   };
names = { ...
   'tblCodeID_Dataset', ...
   'tblCodeID_Param', ...
   'tblCodeID_Matrx', ...
   'intYear', ...
   'tblCodeID_Taxa', ...
   'tblCodeID_Area', ...
   'page', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getESD_DataFormat', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getESD_DataFormat', ...
    soapMessage);
getESD_DataFormatResult = parseSoapResponse(response);
