function getFishTrawlSpeciesResult = getFishTrawlSpecies(obj)
%getFishTrawlSpecies(obj)
%
%   Get the list of Species fish trawl survey in EcoSystemData
%   
%     Input:
%   
%     Output:
%       getFishTrawlSpeciesResult = (ArrayOfSpeciesList)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getFishTrawlSpecies', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getFishTrawlSpecies', ...
    soapMessage);
getFishTrawlSpeciesResult = parseSoapResponse(response);
