function getICESStatisticalRectanglesGridResult = getICESStatisticalRectanglesGrid(obj,layerType,tblCodeID_DataSet,tblCodeID_DType,tblCodeID_Matrx,tblCodeID_Param,tblCodeID_ParGR,tblCodeID_Kingdom,tblCodeID_Phylum,tblCodeID_Class,tblCodeID_Order,tblCodeID_Family,tblCodeID_Genus,tblCodeID_Vernacular,tblCodeID_Species,strYear)
%getICESStatisticalRectanglesGrid(obj,layerType,tblCodeID_DataSet,tblCodeID_DType,tblCodeID_Matrx,tblCodeID_Param,tblCodeID_ParGR,tblCodeID_Kingdom,tblCodeID_Phylum,tblCodeID_Class,tblCodeID_Order,tblCodeID_Family,tblCodeID_Genus,tblCodeID_Vernacular,tblCodeID_Species,strYear)
%
%   Get a density grid of EcoSystemData
%   
%     Input:
%       layerType = (string)
%       tblCodeID_DataSet = (string)
%       tblCodeID_DType = (string)
%       tblCodeID_Matrx = (string)
%       tblCodeID_Param = (string)
%       tblCodeID_ParGR = (string)
%       tblCodeID_Kingdom = (string)
%       tblCodeID_Phylum = (string)
%       tblCodeID_Class = (string)
%       tblCodeID_Order = (string)
%       tblCodeID_Family = (string)
%       tblCodeID_Genus = (string)
%       tblCodeID_Vernacular = (string)
%       tblCodeID_Species = (string)
%       strYear = (string)
%   
%     Output:
%       getICESStatisticalRectanglesGridResult = (ArrayOfICESStatisticalRectanglesGrid)

% Build up the argument lists.
values = { ...
   layerType, ...
   tblCodeID_DataSet, ...
   tblCodeID_DType, ...
   tblCodeID_Matrx, ...
   tblCodeID_Param, ...
   tblCodeID_ParGR, ...
   tblCodeID_Kingdom, ...
   tblCodeID_Phylum, ...
   tblCodeID_Class, ...
   tblCodeID_Order, ...
   tblCodeID_Family, ...
   tblCodeID_Genus, ...
   tblCodeID_Vernacular, ...
   tblCodeID_Species, ...
   strYear, ...
   };
names = { ...
   'layerType', ...
   'tblCodeID_DataSet', ...
   'tblCodeID_DType', ...
   'tblCodeID_Matrx', ...
   'tblCodeID_Param', ...
   'tblCodeID_ParGR', ...
   'tblCodeID_Kingdom', ...
   'tblCodeID_Phylum', ...
   'tblCodeID_Class', ...
   'tblCodeID_Order', ...
   'tblCodeID_Family', ...
   'tblCodeID_Genus', ...
   'tblCodeID_Vernacular', ...
   'tblCodeID_Species', ...
   'strYear', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getICESStatisticalRectanglesGrid', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getICESStatisticalRectanglesGrid', ...
    soapMessage);
getICESStatisticalRectanglesGridResult = parseSoapResponse(response);
