function getListParamGroupResult = getListParamGroup(obj)
%getListParamGroup(obj)
%
%   Get the list of Parameter groups available in the database
%   
%     Input:
%   
%     Output:
%       getListParamGroupResult = (ArrayOfParamGroupList)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getListParamGroup', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getListParamGroup', ...
    soapMessage);
getListParamGroupResult = parseSoapResponse(response);
