function getListDatasetsResult = getListDatasets(obj)
%getListDatasets(obj)
%
%   Get the list and keys of datasets available in the database and the number of mesurements, number of years with measurements and date of the first and last measurement
%   
%     Input:
%   
%     Output:
%       getListDatasetsResult = (ArrayOfDatasetList)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getListDatasets', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getListDatasets', ...
    soapMessage);
getListDatasetsResult = parseSoapResponse(response);
