function getListMatricesResult = getListMatrices(obj)
%getListMatrices(obj)
%
%   Get the list of Matrices in EcoSystemData
%   
%     Input:
%   
%     Output:
%       getListMatricesResult = (ArrayOfMatrixList)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getListMatrices', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getListMatrices', ...
    soapMessage);
getListMatricesResult = parseSoapResponse(response);
