function getListSpeciesResult = getListSpecies(obj)
%getListSpecies(obj)
%
%   Get the list of Species in EcoSystemData
%   
%     Input:
%   
%     Output:
%       getListSpeciesResult = (ArrayOfSpeciesList)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'getListSpecies', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/getListSpecies', ...
    soapMessage);
getListSpeciesResult = parseSoapResponse(response);
