function intersectPointWithAreasResult = intersectPointWithAreas(obj,latitude,longitude)
%intersectPointWithAreas(obj,latitude,longitude)
%
%   This API of the webservice returns a description of an OSPAR Region if the point is contained within any of the OSPAR Regions.
%   
%     Input:
%       latitude = (double)
%       longitude = (double)
%   
%     Output:
%       intersectPointWithAreasResult = (ArrayOfGeographicalAreaList)

% Build up the argument lists.
values = { ...
   latitude, ...
   longitude, ...
   };
names = { ...
   'latitude', ...
   'longitude', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'intersectPointWithAreas', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/intersectPointWithAreas', ...
    soapMessage);
intersectPointWithAreasResult = parseSoapResponse(response);
