function selectOBISSummaryDataResult = selectOBISSummaryData(obj,scientificName,year,dateTime)
%selectOBISSummaryData(obj,scientificName,year,dateTime)
%
%   Select OBIS Schema Species summary
%   
%     Input:
%       scientificName = (string)
%       year = (string)
%       dateTime = (string)
%   
%     Output:
%       selectOBISSummaryDataResult = (ArrayOfOBISSummaryRecord)

% Build up the argument lists.
values = { ...
   scientificName, ...
   year, ...
   dateTime, ...
   };
names = { ...
   'scientificName', ...
   'year', ...
   'dateTime', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'iistest01.ices.local/EcoSystemData', ...
    'selectOBISSummaryData', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'iistest01.ices.local/EcoSystemData/selectOBISSummaryData', ...
    soapMessage);
selectOBISSummaryDataResult = parseSoapResponse(response);
