function pntr = deltarespointer()
pntr = [...
    nan nan nan nan 2   2   2   nan nan nan nan nan nan nan nan nan;...
    nan nan 2   2   2   2   nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan 2   2   2   2   2   2   2   2   2   nan nan nan nan;...
    nan nan nan nan nan 2   2   2   2   2   2   2   nan nan nan nan;...
    nan nan nan nan nan nan 2   2   2   2   2   nan nan nan nan nan;...
    nan nan nan nan 2   2   2   2   2   2   2   2   nan nan nan nan;...
    nan nan nan 2   2   2   2   nan nan nan nan nan nan nan nan nan;...
    nan nan 2   2   2   nan nan 1   1   1   1   1   nan nan nan nan;...
    nan nan 2   nan nan 1   1   1   1   1   1   1   nan nan nan nan;...
    nan nan nan nan 1   1   1   1   1   1   1   nan nan nan nan nan;...
    nan nan nan 1   1   1   1   1   1   1   nan nan nan nan nan nan;...
    nan nan nan 1   1   1   1   1   1   1   1   nan nan nan nan nan;...
    nan nan nan nan nan 1   1   1   1   1   1   nan nan nan nan nan;...
    nan nan nan nan nan nan 1   1   1   1   nan nan nan nan nan nan;...
    nan nan nan nan nan nan 1   1   1   1   nan nan nan nan nan nan;...
    nan nan nan nan 1   1   1   1   nan nan nan nan nan nan nan nan];

%{
% From 16x16 logo
pntr = [...
    NaN,NaN,NaN,1  ,1  ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN;...
    NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN,NaN,NaN;...
    NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN,NaN,NaN;...
    NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN,NaN,NaN;...
    NaN,NaN,NaN,NaN,NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,NaN,NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,NaN,NaN,1  ,1  ,1  ,1  ,1  ,NaN,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,NaN,1  ,1  ,1  ,1  ,NaN,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,1  ,1  ,NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN,NaN;...
    NaN,NaN,1  ,1  ,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,1  ,NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,NaN,NaN,NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN;...
    NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1  ,1  ,1  ,1  ,NaN,NaN,NaN;...
    NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1  ,1  ,1  ,1  ,NaN,NaN,NaN,NaN;...
    NaN,NaN,NaN,1  ,1  ,1  ,1  ,1  ,1  ,1  ,NaN,NaN,NaN,NaN,NaN,NaN];

%}
    
