function pntr = movepointer()
pntr = [...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan 1   1   nan nan nan nan nan nan 1   1   nan nan nan;...
    nan nan 1   1   nan nan nan nan nan nan nan nan 1   1   nan nan;...
    nan 1   1   nan nan nan nan nan nan nan nan nan nan 1   1   nan;...
    1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1  ;...
    1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1  ;...
    nan 1   1   nan nan nan nan nan nan nan nan nan nan 1   1   nan;...
    nan nan 1   1   nan nan nan nan nan nan nan nan 1   1   nan nan;...
    nan nan nan 1   1   nan nan nan nan nan nan 1   1   nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
    nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan];

% pntr = [...
%     nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
%     nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
%     nan nan nan nan 1   1   nan nan nan nan 1   1   nan nan nan nan;...
%     nan nan nan 1   1   nan nan nan nan nan nan 1   1   nan nan nan;...
%     nan nan 1   1   nan nan nan nan nan nan nan nan 1   1   nan nan;...
%     nan 1   1   nan nan nan nan nan nan nan nan nan nan 1   1   nan;...
%     1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1  ;...
%     1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1  ;...
%     nan 1   1   nan nan nan nan nan nan nan nan nan nan 1   1   nan;...
%     nan nan 1   1   nan nan nan nan nan nan nan nan 1   1   nan nan;...
%     nan nan nan 1   1   nan nan nan nan nan nan 1   1   nan nan nan;...
%     nan nan nan nan 1   1   nan nan nan nan 1   1   nan nan nan nan;...
%     nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
%     nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
%     nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan;...
%     nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan];