function v=compute_tangential_surge_d1(phi,foreward_speed)
% Computes tangential_surge_d1
% Script automatically generated by fit_tangential_surge_d1.m
% Inputs : 
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.084059
% RMSE  = 1.6707
% MEAN  = -4.8576
% RANGE = -8.5765 - -2.2956

beta( 1 )= -6.0842e+00 ;
beta( 2 )= -6.1036e-02 ;
beta( 3 )= 7.3948e+01 ;
beta( 4 )= 0.0000e+00 ;

v=beta(1) + beta(2)*foreward_speed .* sin((phi-beta(3))*pi/180);
