function v=compute_tangential_surge_f1(a,vmax,shelf_width,foreward_speed,phi)
% Computes tangential_surge_a1
% Script automatically generated by fit_tangential_surge_a2.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.69836
% RMSE  = 0.16274
% MEAN  = 1.1172
% RANGE = 0.53652 - 1.7939

beta( 1 )= 5.5397e-01 ;
beta( 2 )= -3.3714e-02 ;
beta( 3 )= -2.0368e+02 ;
beta( 4 )= 6.7910e-02 ;
beta( 5 )= 2.4866e-01 ;
beta( 6 )= -3.8723e-02 ;
beta( 7 )= -4.4831e-01 ;

v=beta(1)+beta(2) * (cos((phi-beta(3))*pi/180)) .* foreward_speed.^beta(4).*vmax.^beta(5).*shelf_width.^beta(6).*a.^beta(7);
