function v=compute_tangential_surge_e2(foreward_speed,phi)
% Computes tangential_surge_e2
% Script automatically generated by fit_tangential_surge_e2.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.6479
% RMSE  = 0.53918
% MEAN  = 1.7157
% RANGE = 0.55654 - 4.3177

beta( 1 )= 4.2695e-02 ;
beta( 2 )= 3.2746e+01 ;
beta( 3 )= 1.0000e+00 ;

v=beta(1) + beta(2) ./ (foreward_speed.*cos(phi*pi/180));
