function v=compute_tangential_surge_c2(a,rmax,vmax,shelf_width,phi,foreward_speed)
% Computes tangential_surge_c2
% Script automatically generated by fit_tangential_surge_c2.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.85584
% RMSE  = 7.0116
% MEAN  = 74.036
% RANGE = 37.0802 - 112.9081

beta( 1 )= 1.2812e+00 ;
beta( 2 )= 1.0128e-01 ;
beta( 3 )= 3.4467e+01 ;
beta( 4 )= 5.1485e-01 ;
beta( 5 )= 3.6547e-01 ;
beta( 6 )= 3.4027e-02 ;
beta( 7 )= -3.2606e-01 ;
beta( 8 )= 6.7721e+01 ;
beta( 9 )= -1.5458e-02 ;

v=beta(1) * a.^beta(2) .* max(shelf_width,beta(3)).^beta(4) .* rmax.^beta(5) .* vmax.^beta(6) .* (1 + beta(7)*sin((phi-beta(8))*pi/180)) .* foreward_speed.^beta(9);
