function v=compute_tangential_surge_a1(a,vmax,shelf_width,foreward_speed,phi)
% Computes tangential_surge_a1
% Script automatically generated by fit_tangential_surge_a1.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.82881
% RMSE  = 0.049513
% MEAN  = 0.21327
% RANGE = 0.10293 - 0.59645

beta( 1 )= 3.7335e-04 ;
beta( 2 )= 2.9230e-02 ;
beta( 3 )= 3.4115e-01 ;
beta( 4 )= 1.0000e+00 ;
beta( 5 )= 3.6261e-02 ;
beta( 6 )= 9.3323e-01 ;

v=beta(1) * exp(-a/beta(2)) .* shelf_width.^beta(3) .* (beta(4)+beta(5).*foreward_speed.*cos(phi*pi/180)) .* vmax.^beta(6);
