function v=compute_tangential_surge_e1(foreward_speed,shelf_width)
% Computes tangential_surge_e1
% Script automatically generated by fit_tangential_surge_e1.m
% Inputs : 
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)

% R2    = 0.22423
% RMSE  = 3.7328
% MEAN  = 9.1186
% RANGE = 5.0782 - 23.0474

beta( 1 )= 7.8346e+00 ;
beta( 2 )= 8.6800e-05 ;
beta( 3 )= 3.9361e+00 ;
beta( 4 )= 2.5613e+00 ;

v = beta(1) + beta(2) * exp(-foreward_speed/beta(3)) .* shelf_width.^beta(4);
