function v=compute_tangential_surge_f2(a,vmax,shelf_width,foreward_speed,phi)
% Computes tangential_surge_a1
% Script automatically generated by fit_tangential_surge_a2.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.65586
% RMSE  = 0.082112
% MEAN  = 1.1083
% RANGE = 0.86226 - 1.4444

beta( 1 )= 9.7401e-01 ;
beta( 2 )= 7.2633e-02 ;
beta( 3 )= -2.2144e+02 ;
beta( 4 )= 8.7756e-01 ;
beta( 5 )= -3.9754e-01 ;
beta( 6 )= 2.1521e-01 ;
beta( 7 )= -3.2197e-02 ;

v=beta(1)+beta(2) * (1+cos((phi-beta(3))*pi/180)) .* foreward_speed.^beta(4).*vmax.^beta(5).*shelf_width.^beta(6).*a.^beta(7);
