function [standard_name,code] = donarname2standardnames(deltares_name)
%DELTARESNAME2STANDARDNAMES
%
% [standard_name,code] = deltaresname2standardnames(deltares_name)
%
% See also: 

% code - standard_name - deltares_name

parameter_database = { ...
'Fluorescence_in_U_in_surface_water',                                       'sea_water_fluorescence',                     'fluorescence'; ...
'Conductivity_in_mS/m_with_respect_to_20_degrees_celsius_in_surface_water', 'sea_water_electrical_conductivity',          'conductivity'; ...
'Irradiation_in_uE_in_air',                                                 'downwelling_longwave_radiance_in_air',       'air_radiance'; ...
'Irradiation_in_uE_in_surface_water',                                       'downwelling_radiance_in_sea_water',          'water_radiance'; ...
'Turbidity_in_NTU_in_surface_water',                                        'sea_water_turbidity',                        'turbidity';...
'Acidity_in_surface_water',                                                 'sea_water_ph_reported_on_total_scale',       'ph'; ...
'Salinity_in_surface_water',                                                'sea_water_salinity',                         'salinity'; ...
'Temperature_in_oC_in_surface_water',                                       'sea_water_temperature',                      'temperature'; ...
'Oxygen_in_mg/l_in_surface_water',                                          'mass_concentration_of_oxygen_in_sea_water',  'oxygen'; ...
};

if isempty(find(strcmpi(parameter_database(:,3),deltares_name)))
    error(['deltares_name: ',deltares_name,' not found in database.']);
end

code          = parameter_database{strcmpi(parameter_database(:,3),deltares_name),1};
standard_name = parameter_database{strcmpi(parameter_database(:,3),deltares_name),2};
deltares_name = parameter_database{strcmpi(parameter_database(:,3),deltares_name),3};;
