function station = getDataInventory(obj,stationId)
%getDataInventory(obj,stationId)
%
%     Input:
%       stationId = (string)
%   
%     Output:
%       station = (station)

% Build up the argument lists.
values = { ...
   stationId, ...
   };
names = { ...
   'stationId', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/datainventory/wsdl', ...
    'getDataInventory', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
station = parseSoapResponse(response);
