%RWS_WATERBASE2NC_PLOT   example how to plot netCDF file from OPeNDAP server
%
%   plot and load netCDf file generated by GETWATERBASE2NC_TIME_DIRECT
%
%See also: RWS_WATERBASE_GET_URL, RWS_WATERBASE2NC

% $Id: rws_waterbase2nc_plot.m 2116 2009-12-28 15:35:42Z boer_g $
% $Date: 2009-12-28 23:35:42 +0800 (Mon, 28 Dec 2009) $
% $Author: boer_g $
% $Revision: 2116 $
% $HeadURL: https://svn.oss.deltares.nl/repos/openearthtools/trunk/matlab/applications/Rijkswaterstaat/rws_waterbase2nc_plot.m $

   OPT.substance_code = 'id1';
   OPT.station_code   = 'DENHDR';
   OPT.timeframe      = '196101010000-200801010000'
   outputfile         = ['http://dtvirt5.deltares.nl:8080/thredds/dodsC/opendap/rijkswaterstaat/waterbase.nl/sea_surface_height/',...
                          OPT.substance_code,'-',...
                          OPT.station_code,'-',...
                          OPT.timeframe,'_time_direct.nc'];
   
   [D,M]=nc_cf_stationTimeSeries(outputfile,'sea_surface_height')

%%EOF