% mte = mtestengine(...
%     'maindir',fullfile(mctoolsroot,'matlab','applications','DUROS'),...
%     'template','oet',...
%     'targetdir',fullfile(mctoolsroot,'matlab','applications','DUROS','testbank','temptestresult'),...
%     'recursive',true);

mtr = MTestRunner(...
    'MainDir',fullfile(oetroot,'applications','DUROS'),...
    'Template','oet',...
    'TargetDir',fullfile(mctoolsroot,'matlab','applications','DUROS','testbank','temptestresult'),...
    'Recursive',true);

mtr.gathertests;

mtr.Tests(end+1) = MTest('roundoff_test');
mtr.Tests(end+1) = MTest('getCumVolume_test');
mtr.Tests(end+1) = MTest('getG_test');
mtr.Tests(end+1) = MTest('getBoundaryProfile_test');
mtr.Tests(end+1) = MTest('getParabolicProfile_test');
mtr.maindir = 'f:\';

mtr.run;