function v=compute_ekman_surge_cnx(shelf_width,phi)
% Computes ekman_surge_cnx
% Script automatically generated by fit_ekman_surge_cnx.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)

% R2    = 0.38201
% RMSE  = 44.4122
% MEAN  = 178.6367
% RANGE = 72.0424 - 291.2003

beta( 1 )= 7.0321e+00 ;
beta( 2 )= 2.8447e-01 ;
beta( 3 )= 4.0567e-01 ;

v=beta(1)*shelf_width.^beta(2).*(90-phi).^beta(3);
