function v=compute_ekman_surge_fpx(shelf_width,phi)
% Computes ekman_surge_xmin
% Script automatically generated by fit_ekman_surge_xmin.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.14328
% RMSE  = 0.0048284
% MEAN  = 0.0073648
% RANGE = 0.00073394 - 0.023213

beta( 1 )= 7.5956e-03 ;
beta( 2 )= -1.1476e-05 ;
beta( 3 )= -4.0370e-03 ;
beta( 4 )= 3.2212e+01 ;

v=beta(1) + beta(2)*shelf_width + beta(3)*sin((phi-beta(4))*pi/180);
