function v=compute_ekman_surge_semax(a,vmax,shelf_width,foreward_speed,phi,r35,latitude,manning)
% Computes ekman_surge_semax
% Script automatically generated by fit_ekman_surge_semax.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.91881
% RMSE  = 0.16085
% MEAN  = 0.93991
% RANGE = 0.16625 - 2.3964

beta( 1 )= 3.0218e-05 ;
beta( 2 )= 5.9728e-02 ;
beta( 3 )= 7.1346e+01 ;
beta( 4 )= 3.9711e-01 ;
beta( 5 )= 4.9337e-01 ;
beta( 6 )= 7.2242e-01 ;
beta( 7 )= 7.4198e-01 ;
beta( 8 )= -5.5663e-01 ;
beta( 9 )= -5.5313e-02 ;

v=beta(1) * exp(-a/beta(2)) .* tanh(shelf_width/beta(3)) .* (1+beta(4)*sin(phi*pi/180))  .* vmax.^beta(5)  .* r35.^beta(6)  .* latitude.^beta(7)  .* manning.^beta(8)   .* foreward_speed.^beta(9);
