function v=compute_ekman_surge_enx(shelf_width,a,vmax,phi)
% Computes ekman_surge_xmin
% Script automatically generated by fit_ekman_surge_xmin.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.10399
% RMSE  = 0.0025112
% MEAN  = -0.00073714
% RANGE = -0.0067725 - 0.0058766

beta( 1 )= -3.2854e-03 ;
beta( 2 )= 4.8305e-06 ;
beta( 3 )= 2.8284e-02 ;
beta( 4 )= -5.7961e-06 ;
beta( 5 )= 2.3813e-03 ;
beta( 6 )= -7.0000e+01 ;
beta( 7 )= 0.0000e+00 ;
beta( 8 )= 0.0000e+00 ;
beta( 9 )= 0.0000e+00 ;

v=beta(1) + beta(2)*shelf_width + beta(3)*a + beta(4)*vmax + beta(5)*sin((phi-beta(6))*pi/180);
