function v=compute_ekman_surge_a1p(vmax,foreward_speed,phi,r35)
% Computes ekman_surge_a1p
% Script automatically generated by fit_ekman_surge_a1p.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.63538
% RMSE  = 2.0127
% MEAN  = 6.4287
% RANGE = 2.0566 - 15.7622

beta( 1 )= 2.2972e+01 ;
beta( 2 )= -8.6690e-01 ;
beta( 3 )= -3.8606e-01 ;
beta( 4 )= 5.7029e-01 ;

v=beta(1)*(cos(phi*pi/180).*foreward_speed).^beta(2).*vmax.^beta(3).*r35.^beta(4);
