function v=compute_ekman_surge_cexp(vmax,rmax,r35,vt,phi,phi_in,w,a,n,lat)
% Computes ekman_surge_cexp
% Script automatically generated by fit_ekman_surge_cexp.m
% Inputs : 
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% r35            = R35 (km)
% vt             = forward speed (km/h)
% phi            = track angle (deg)
% phi_in         = inflow angle (deg)
% w              = shelf width (km)
% a              = Dean slope a (-)
% n              = Mannings n
% lat            = latitude (deg)

% R2    = 0.7682
% RMSE  = 20.1338
% MEAN  = 131.239
% RANGE = 75.7646 - 253.466

beta( 1 )= 8.4362e+01 ;
beta( 2 )= 3.9702e+01 ;
beta( 3 )= 1.2198e+00 ;
beta( 4 )= 7.9760e-01 ;
beta( 5 )= 6.4803e-01 ;
beta( 6 )= -9.0297e-01 ;
beta( 7 )= -2.6342e-01 ;
beta( 8 )= -2.1481e-01 ;
beta( 9 )= 5.5095e-01 ;
beta( 10 )= -5.8207e-01 ;
beta( 11 )= 2.8553e+01 ;
beta( 12 )= -5.5711e-01 ;
beta( 13 )= -3.8117e-01 ;
beta( 14 )= 2.2701e-02 ;
beta( 15 )= 2.7000e+01 ;

v=beta(1) + beta(2)*w.^beta(3) .* min(a,beta(14)).^beta(4) .* r35.^beta(5) .* rmax.^beta(13) .* (1+beta(10)*cos((phi-beta(11))*pi/180)) .* vmax.^beta(6) .* max(phi_in,5).^beta(7) .* n.^beta(8) .* lat.^beta(9) .* vt.^beta(12);
