function v=compute_ekman_surge_t0p(a,r35,shelf_width,foreward_speed,phi,vmax)
% Computes ekman_surge_t0p
% Script automatically generated by fit_ekman_surge_t0p.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.74254
% RMSE  = 2.2644
% MEAN  = 4.7379
% RANGE = 0.16667 - 16.3333

beta( 1 )= 2.4919e+00 ;
beta( 2 )= 4.4307e-01 ;
beta( 3 )= -1.0000e+00 ;
beta( 4 )= -3.4107e+00 ;
beta( 5 )= -5.6589e-02 ;
beta( 6 )= 4.1703e-01 ;
beta( 7 )= 3.7247e+01 ;
beta( 8 )= -1.3197e-01 ;

v=beta(4)+beta(1).*r35.^beta(2).*(foreward_speed.*cos(phi*pi/180)).^beta(3).*a.^beta(5).*max(shelf_width,beta(7)).^beta(6).*vmax.^beta(8);
v=max(v,0);
