function v=compute_ekman_surge_de(a,shelf_width,foreward_speed,phi,latitude)
% Computes ekman_surge_de
% Script automatically generated by fit_ekman_surge_de.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.22657
% RMSE  = 0.00915
% MEAN  = 0.0013547
% RANGE = -0.015161 - 0.026243

beta( 1 )= 3.6612e-03 ;
beta( 2 )= 4.6583e-04 ;
beta( 3 )= 5.4644e-01 ;
beta( 4 )= 2.3949e+01 ;
beta( 5 )= 7.6499e-01 ;

v=beta(1) + beta(2)*sin((phi-beta(4))*pi/180).* foreward_speed .* shelf_width.^beta(3) .* a.^beta(5) ./ sin(max(latitude,2)*pi/180);
