function v=compute_ekman_surge_aen(vmax,rmax,r35,vt,phi,phi_in,w,a,n,lat)
% Computes ekman_surge_aen
% Script automatically generated by fit_ekman_surge_aen.m
% Inputs : 
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% r35            = R35 (km)
% vt             = forward speed (km/h)
% phi            = track angle (deg)
% phi_in         = inflow angle (deg)
% w              = shelf width (km)
% a              = Dean slope a (-)
% n              = Mannings n
% lat            = latitude (deg)

% R2    = 0.84863
% RMSE  = 0.11686
% MEAN  = 0.40395
% RANGE = 0.029478 - 1.2337

beta( 1 )= 1.9710e-06 ;
beta( 2 )= 4.0973e-02 ;
beta( 3 )= 5.1679e-01 ;
beta( 4 )= -3.8334e-01 ;
beta( 5 )= -5.5322e+01 ;
beta( 6 )= 8.1896e-01 ;
beta( 7 )= 3.2900e-01 ;
beta( 8 )= 8.4503e-01 ;
beta( 9 )= -4.3864e-01 ;
beta( 10 )= -2.0327e-01 ;
beta( 11 )= 2.3233e-01 ;

v=beta(1) * exp(-a/beta(2)) .* w.^beta(3) .* (1+beta(4)*sin((phi-beta(5))*pi/180))  .* vmax.^beta(6)  .* r35.^beta(7)  .* lat.^beta(8)  .* n.^beta(9) .* vt.^beta(10)  .* rmax.^beta(11);
