function v=compute_ekman_surge_a2n(vmax,shelf_width,foreward_speed,phi,r35)
% Computes ekman_surge_a2n
% Script automatically generated by fit_ekman_surge_a2n.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

beta( 1 )= 6.3945e+00 ;
beta( 2 )= 3.5725e-01 ;
beta( 3 )= 8.4314e-01 ;
beta( 4 )= -1.0726e+00 ;
beta( 5 )= -8.8175e-01 ;
beta( 6 )= 8.8705e-01 ;

v=beta(1)+beta(2)*shelf_width.^beta(3).*(cos(phi*pi/180).*foreward_speed).^beta(4).*vmax.^beta(5).*r35.^beta(6);
