function v=compute_ekman_surge_t0n(a,vmax,shelf_width,foreward_speed,phi,r35)
% Computes ekman_surge_t0n
% Script automatically generated by fit_ekman_surge_t0n.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.31726
% RMSE  = 1.7362
% MEAN  = 5.5617
% RANGE = 1.6667 - 9.6667

beta( 1 )= 6.9970e-01 ;
beta( 2 )= 3.2288e-01 ;
beta( 3 )= -6.8291e-02 ;
beta( 4 )= 0.0000e+00 ;
beta( 5 )= 3.6050e-01 ;
beta( 6 )= 3.9610e-01 ;
beta( 7 )= 9.3018e+01 ;

v=beta(4)+beta(1).*r35.^beta(2).*(foreward_speed.*cos(phi*pi/180)).^beta(3).*a.^beta(5).*max(shelf_width,beta(7)).^beta(6);
