function v=compute_ekman_surge_semax(a,shelf_width,phi,vmax,r35,latitude,manning)
% Computes ekman_surge_semin
% Script automatically generated by fit_ekman_surge_semin.m
% Inputs : 
% a              = a (-)
% shelf_width    = width (km)
% phi            = track angle (deg)
% vmax           = Vmax (km/h)
% r35            = R35 (km)
% latitude       = degrees
% manning        = Mannings n

% R2    = 0.80254
% RMSE  = 0.15029
% MEAN  = 0.39543
% RANGE = 0.022565 - 1.3687

beta( 1 )= 1.1778e-05 ;
beta( 2 )= 3.3335e-02 ;
beta( 3 )= 4.7247e-01 ;
beta( 4 )= -4.0956e-01 ;
beta( 5 )= -6.4250e+01 ;
beta( 6 )= 6.7200e-01 ;
beta( 7 )= 3.4970e-01 ;
beta( 8 )= 7.8216e-01 ;
beta( 9 )= -4.1944e-01 ;
beta( 10 )= -5.4161e-02 ;

v=beta(1) * exp(-a/beta(2)) .* shelf_width.^beta(3) .* (1+beta(4)*sin((phi-beta(5))*pi/180))  .* vmax.^beta(6)  .* r35.^beta(7)  .* latitude.^beta(8)  .* manning.^beta(9);
