function v=compute_ekman_surge_t0(a,vmax,shelf_width,foreward_speed,phi,manning)
% Computes ekman_surge_t0
% Script automatically generated by fit_ekman_surge_t0.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.64367
% RMSE  = 1.0775
% MEAN  = 0.72188
% RANGE = -4.0005 - 4.0305

beta( 1 )= -3.3710e+00 ;
beta( 2 )= 5.0767e+01 ;
beta( 3 )= -6.0392e-03 ;
beta( 4 )= 2.4596e+00 ;
beta( 5 )= -6.1509e+01 ;
beta( 6 )= 3.1691e+00 ;
beta( 7 )= 1.0000e+01 ;
beta( 8 )= 9.2427e+00 ;
beta( 9 )= 1.7565e+01 ;
beta( 10 )= 4.6866e+01 ;
beta( 11 )= -6.6500e+01 ;

v=beta(1)+(beta(2)*a) + (beta(3)*shelf_width) + beta(4)*(sin((phi-beta(5))*pi/180)) + beta(6)*tanh((foreward_speed-beta(7))/beta(8)) + beta(9)*(exp(-vmax/beta(10))) + beta(11)*manning;
