function v=compute_ekman_surge_a2p(shelf_width,foreward_speed,phi,a)
% Computes ekman_surge_a2p
% Script automatically generated by fit_ekman_surge_a2p.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

beta( 1 )= 2.5277e+01 ;
beta( 2 )= -5.3849e-01 ;
beta( 3 )= -8.5388e+00 ;
beta( 4 )= -6.2902e-01 ;
beta( 5 )= 4.1123e-01 ;
beta( 6 )= 2.5567e-01 ;

v=beta(1)*(1+beta(2)*cos((phi-beta(3))*pi/180)).*foreward_speed.^beta(4).*shelf_width.^beta(5).*a.^beta(6);
