function v=compute_ekman_surge_cexn(vmax,rmax,r35,vt,phi,phi_in,w,a,n,lat)
% Computes ekman_surge_cexn
% Script automatically generated by fit_ekman_surge_cexn.m
% Inputs : 
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% r35            = R35 (km)
% vt             = forward speed (km/h)
% phi            = track angle (deg)
% phi_in         = inflow angle (deg)
% w              = shelf width (km)
% a              = Dean slope a (-)
% n              = Mannings n
% lat            = latitude (deg)

% R2    = 0.50734
% RMSE  = 41.7192
% MEAN  = 186.6701
% RANGE = 75.2247 - 293.4576

beta( 1 )= 4.4891e+00 ;
beta( 2 )= 3.3645e-01 ;
beta( 3 )= 4.6591e-01 ;

v=beta(1)*w.^beta(2).*(90-phi).^beta(3);
