function v=compute_ekman_surge_epx(shelf_width,a,foreward_speed,latitude,r35,phi_spiral)
% Computes ekman_surge_xmin
% Script automatically generated by fit_ekman_surge_xmin.m
% Inputs : 
% a              = a (-)
% vmax           = Vmax (km/h)
% shelf_width    = width (km)
% foreward_speed = foreward speed (km/h)
% phi            = track angle (deg)

% R2    = 0.51552
% RMSE  = 0.00094212
% MEAN  = -0.00041703
% RANGE = -0.0028007 - 0.0029844

beta( 1 )= -1.6839e-03 ;
beta( 2 )= 5.5820e-03 ;
beta( 3 )= 7.2713e+01 ;
beta( 4 )= -1.9083e-02 ;
beta( 5 )= 4.4904e-05 ;
beta( 6 )= -5.2403e-05 ;
beta( 7 )= 2.7503e-06 ;
beta( 8 )= 4.1415e-05 ;

v=beta(1) + beta(2)*exp(-shelf_width/beta(3)) + beta(4)*a + beta(5)*foreward_speed + beta(6)*latitude + beta(7)*r35 + beta(8)*phi_spiral;
