function [datums,MinMaxWL] = getDatums(obj,stationId,epoch,unit)
%getDatums(obj,stationId,epoch,unit)
%
%     Input:
%       stationId = (string)
%       epoch = (string)
%       unit = (int)
%   
%     Output:
%       datums = (datums)
%       MinMaxWL = (MinMaxWL)

% Build up the argument lists.
values = { ...
   stationId, ...
   epoch, ...
   unit, ...
   };
names = { ...
   'stationId', ...
   'epoch', ...
   'unit', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/datums/wsdl', ...
    'getDatums', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
[datums,MinMaxWL] = parseSoapResponse(response);
