function [stationId,stationName,latitude,longitude,state,dataSource,status,epoch,unit,elevation,datums,MinMaxWL] = getDatumsAndMetadata(obj,stationId,epoch,unit)
%getDatumsAndMetadata(obj,stationId,epoch,unit)
%
%     Input:
%       stationId = (string)
%       epoch = (string)
%       unit = (int)
%   
%     Output:
%       stationId = (string)
%       stationName = (string)
%       latitude = (float)
%       longitude = (float)
%       state = (string)
%       dataSource = (string)
%       status = (string)
%       epoch = (string)
%       unit = (string)
%       elevation = (string)
%       datums = (datums)
%       MinMaxWL = (MinMaxWL)

% Build up the argument lists.
values = { ...
   stationId, ...
   epoch, ...
   unit, ...
   };
names = { ...
   'stationId', ...
   'epoch', ...
   'unit', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/datums/wsdl', ...
    'getDatumsAndMetadata', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
[stationId,stationName,latitude,longitude,state,dataSource,status,epoch,unit,elevation,datums,MinMaxWL] = parseSoapResponse(response);
