
% rmdir('D:\products\kml\projects\363096_ichthys_lng_facilities\bathymetry_grids\sp1_mof_025X025\tmp');
% winopen('D:\products\kml\projects\363096_ichthys_lng_facilities\bathymetry_grids\sp1_mof_025X025\tmp')
ncgentools_surface_kml(...
    'path_netcdf','D:\products\nc\projects\363096_ichthys_lng_facilities\bathymetry_grids\sp1_mof_025X025\reference',...
    'path_kml','D:\products\kml\projects\363096_ichthys_lng_facilities\bathymetry_grids\sp1_mof_025X025\reference',...
    'descriptivename','sp1_mof_025X025',...
    'CBtemplateVer','KML_colorbar_template_vertical_vanoord.png',...
    'lowestLevel',20,...
    'lighting_effects',true,...
    'colorMap',@(m) jet(m),...
    'cLim',[-1.5 5.5],...
    'z_scale_factor',-1,...
    'timerange',[now-5 now]);
