function varargout=jarkus_area_definition
%JARKUS_AREA_DEFINITION  definition (code and name) of 15 jarkus areas
%
%  [flag_values,flag_meanings]=jarkus_area_definition
%
%   2 - Schiermonnikoog  
%   3 - Ameland          
%   4 - Terschelling     
%   5 - Vlieland         
%   6 - Texel            
%   7 - Noord-Holland    
%   8 - Rijnland         
%   9 - Delfland         
%  10 - Maasvlakte       
%  11 - Voorne           
%  12 - Goeree           
%  13 - Schouwen         
%  15 - Noord-Beveland   
%  16 - Walcheren        
%  17 - Zeeuws-Vlaanderen
%
%See also: vaklodingen_definition

    flag_values   = [    2 3 4 5 6 7 8 9 10 11 12 13    15 16 17]; % 1 and 14 are gaps, so 15 in total
    flag_meanings = {...
                     'Schiermonnikoog',...
                     'Ameland',...
                     'Terschelling',...
                     'Vlieland',...
                     'Texel',...
                     'Noord-Holland',...
                     'Rijnland',...
                     'Delfland',...
                     'Maasvlakte',...
                     'Voorne',...
                     'Goeree',...
                     'Schouwen',...
                     ...
                     'Noord-Beveland',...
                     'Walcheren',...
                     'Zeeuws-Vlaanderen'};
if nargout==0
   disp('code - name')
   disp([addrowcol(num2str(flag_values',' %d'),0,1,' '),char(flag_meanings)]);
else
   varargout = {flag_values,flag_meanings};
end

