function v=compute_inflow_surge_amax(vmax,phi_spiral,shelf_width,a,track_angle)
% Computes inflow surge magnitude
% Script automatically generated by fit_inflow_surge_amax.m
% Inputs : 
% vmax        = Vmax (km/h)
% phi_piral   = inflow angle (deg)
% shelf_width = width (km)
% a           = Dean slope (-)
% track_angle = track angle (deg)

% R2    = 0.79149
% RMSE  = 0.13303
% MEAN  = 0.36833
% RANGE = 0.049323 - 1.3039

beta( 1 )= 5.6447e-05 ;
beta( 2 )= 2.1278e-01 ;
beta( 3 )= 2.6441e-01 ;

v=beta(1).*vmax.*sin(phi_spiral*pi/180).*shelf_width.^beta(2).*a.^-1.*(1+beta(3).*sin(track_angle*pi/180));
