function v=compute_inflow_surge_bt(shelf_width,track_angle,foreward_speed,a)
% Computes inflow surge t shift
% Script automatically generated by fit_inflow_surge_bt.m
% Inputs : 
% shelf_width = width (km)
% track_angle = track angle (deg)
% foreward_speed = speed (km/h)
% a = Dean slope (-)

% R2    = 0.85977
% RMSE  = 1.0332
% MEAN  = 2.9687
% RANGE = -1.7587 - 9.6211

beta( 1 )= -6.0125e+00 ;
beta( 2 )= 7.7915e+01 ;
beta( 3 )= 5.3443e-01 ;
beta( 4 )= 2.9132e-01 ;
beta( 5 )= 5.9573e-01 ;

v=beta(1)+beta(2).*(cos(track_angle*pi/180).*foreward_speed).^-1 + beta(3).*a.^beta(4).*shelf_width.^beta(5);
