function v=compute_inflow_surge_bx(vmax,rmax,r35,vt,phi,phi_in,w,a,n,lat)
% Computes inflow surge x shift
% Script automatically generated by fit_inflow_surge_bx.m
% Inputs : 
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% r35            = R35 (km)
% vt             = forward speed (km/h)
% phi            = track angle (deg)
% phi_in         = inflow angle (deg)
% w              = shelf width (km)
% a              = Dean slope a (-)
% n              = Mannings n
% lat            = latitude (deg)

% R2    = 0.49419
% RMSE  = 8.5767
% MEAN  = -8.2662
% RANGE = -32.9629 - 14.5224

beta( 1 )= -9.8527e+00 ;
beta( 2 )= -1.8154e-03 ;
beta( 3 )= -4.6090e+01 ;
beta( 4 )= 1.6172e+00 ;
beta( 5 )= -2.7520e-01 ;
beta( 6 )= 2.3874e+02 ;
beta( 7 )= 2.9643e-01 ;

v=beta(1)+beta(2).*sin((phi-beta(3))*pi/180).*r35.^beta(4) + beta(5)*phi_in + beta(6)*a + beta(7)*vt;
