function v=compute_inflow_surge_bx(track_angle)
% Computes inflow surge x shift
% Script automatically generated by fit_inflow_surge_bx.m
% Inputs : 
% track_angle = track angle (deg)

% R2    = 0.19396
% RMSE  = 11.8028
% MEAN  = -10.0357
% RANGE = -37.0878 - 14.6159

beta( 1 )= -3.1881e+00 ;
beta( 2 )= -1.3690e+01 ;
beta( 3 )= -4.0669e+01 ;

v=beta(1)+beta(2).*sin((track_angle-beta(3))*pi/180);
