%function v=compute_inflow_surge_cx(vmax,rmax,r35,vt,phi,phi_in,w,a,n,lat)
function v=compute_inflow_surge_cx(w,r35)
% Computes inflow surge cx shift
% Script automatically generated by fit_inflow_surge_cx.m
% Inputs : 
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% r35            = R35 (km)
% vt             = forward speed (km/h)
% phi            = track angle (deg)
% phi_in         = inflow angle (deg)
% w              = shelf width (km)
% a              = Dean slope a (-)
% n              = Mannings n
% lat            = latitude (deg)

% R2    = 0.72006
% RMSE  = 20.0447
% MEAN  = 114.7196
% RANGE = 26.4471 - 188.9999

beta( 1 )= 4.0117e-01 ;
beta( 2 )= 6.2523e-01 ;
beta( 3 )= 4.2605e-01 ;

v=beta(1).*w.^beta(2).*r35.^beta(3);
