function data = getCurrents(obj,stationId,beginDate,endDate,binNumber)
%getCurrents(obj,stationId,beginDate,endDate,binNumber)
%
%     Input:
%       stationId = (string)
%       beginDate = (string)
%       endDate = (string)
%       binNumber = (string)
%   
%     Output:
%       data = (ArrayOfData)

% Build up the argument lists.
values = { ...
   stationId, ...
   beginDate, ...
   endDate, ...
   binNumber, ...
   };
names = { ...
   'stationId', ...
   'beginDate', ...
   'endDate', ...
   'binNumber', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/surveycurrents/wsdl', ...
    'getCurrents', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
data = parseSoapResponse(response);
