function v=compute_normal_surge_land_reduction_factor(vmax,track_angle,a,shelf_width,rmax,r35)
% Computes normal surge reduction factor
% Script automatically generated by fit_normal_surge_reduction_factor.m
% Inputs : 
% vmax        = Vmax (km/h)
% r35         = R35 (km)
% track_angle = track angle (deg)
% a           = Dean slope (-)

% R2    = 0.71071
% RMSE  = 0.045927
% MEAN  = 0.70902
% RANGE = 0.51504 - 0.84883

beta( 1 )= 1.4825e+00 ;
beta( 2 )= 2.6671e+02 ;
beta( 3 )= 1.2511e-01 ;
beta( 4 )= 1.1663e+02 ;
beta( 5 )= 2.1017e-01 ;
beta( 6 )= -1.6699e-01 ;
beta( 7 )= -2.6948e-01 ;

v = 1.0 - beta(1)*exp(-vmax/beta(2)).*(1+cos(track_angle*pi/180)).*a.^beta(3).*max(shelf_width,beta(4)).^beta(5).*rmax.^beta(6).*r35.^beta(7);
