function v=compute_normal_surge_cross_track_shift(shelf_width,vmax,rmax,phi,r35,a,foreward_speed)
% Computes normal surge cross-track shift (in km)
% Script automatically generated by fit_normal_surge_cross_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% phi            = track angle (deg)
% r35            = R35 (km)
% a              = Dean slope a (-)

% R2    = 0.85288
% RMSE  = 2.5773
% MEAN  = 17.8351
% RANGE = 3.3338 - 30.1795

beta( 1 )= -4.0837e+00 ;
beta( 2 )= 2.6561e+00 ;
beta( 3 )= 1.7127e+02 ;
beta( 4 )= 3.4790e-01 ;
beta( 5 )= -2.0279e-01 ;
beta( 6 )= 2.0112e-01 ;
beta( 7 )= 2.8069e-01 ;
beta( 8 )= 1.2116e-01 ;
beta( 9 )= -7.3508e-02 ;

v=beta(1) + beta(2)*min(shelf_width,beta(3)).^beta(4).*vmax.^beta(5).*rmax.^beta(6).*cos(phi*pi/180).*r35.^beta(7).*a.^beta(8).*foreward_speed.^beta(9);
