function v=compute_normal_surge_reduction_factor(shelf_width,rmax,track_angle,foreward_speed)
% Computes normal surge reduction factor
% Script automatically generated by fit_normal_surge_reduction_factor.m
% Inputs : 
% shelf_width = width (km)
% rmax        = Rmax (km)
% track_angle = track angle (deg)
% foreward_speed = vt (km/h)

% R2    = 0.9172
% RMSE  = 0.041709
% MEAN  = 0.69215
% RANGE = 0.45745 - 0.9582

beta( 1 )= 1.6849e+00 ;
beta( 2 )= 9.9093e-01 ;
beta( 3 )= 2.8639e+01 ;
beta( 4 )= 3.2919e+01 ;
beta( 5 )= 1.8708e-01 ;
beta( 6 )= 2.4277e+02 ;
beta( 7 )= -9.5254e-02 ;

v=beta(1) - beta(2)*(max(shelf_width,beta(3))/beta(4)).^beta(5).*exp(-(rmax/beta(6))).*(1+beta(7)*cos(track_angle*pi/180));
