function v=compute_normal_surge_along_track_shift(shelf_width,phi,a)
% Computes normal surge along-track shift (in km)
% Script automatically generated by fit_along_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)
% a              = dean slope (-)

% R2    = 0.94638
% RMSE  = 3.3169
% MEAN  = 1.338
% RANGE = -23.0534 - 28.152

beta( 1 )= 1.9492e+00 ;
beta( 2 )= -1.8147e+00 ;
beta( 3 )= 3.5054e-01 ;
beta( 4 )= -2.6031e-01 ;

v=beta(1) + beta(2)*sin(phi*pi/180).*shelf_width.^beta(3).*a.^beta(4);
