function v=compute_normal_surge_reduction_factor(shelf_width,rmax,track_angle,foreward_speed)
% Computes normal surge reduction factor
% Script automatically generated by fit_normal_surge_reduction_factor.m
% Inputs : 
% shelf_width = width (km)
% rmax        = Rmax (km)
% track_angle = track angle (deg)
% foreward_speed = vt (km/h)

% R2    = 0.91461
% RMSE  = 0.042637
% MEAN  = 0.6948
% RANGE = 0.4598 - 0.9611

beta( 1 )= 1.6544e+00 ;
beta( 2 )= 1.0601e+00 ;
beta( 3 )= 2.8161e+01 ;
beta( 4 )= 5.5912e+01 ;
beta( 5 )= 1.9380e-01 ;
beta( 6 )= 2.3907e+02 ;
beta( 7 )= -9.8649e-02 ;

v=beta(1) - beta(2)*(max(shelf_width,beta(3))/beta(4)).^beta(5).*exp(-(rmax/beta(6))).*(1+beta(7)*cos(track_angle*pi/180));
