function v=compute_normal_surge_cross_track_shift(shelf_width,vmax,rmax,phi,r35,a)
% Computes normal surge cross-track shift (in km)
% Script automatically generated by fit_normal_surge_cross_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% vmax           = Vmax (km/h)
% rmax           = Rmax (km)
% phi            = track angle (deg)
% r35            = R35 (km)
% a              = Dean slope a (-)

% R2    = 0.79149
% RMSE  = 3.0631
% MEAN  = 17.2939
% RANGE = 3.3508 - 29.8987

beta( 1 )= -3.5106e+00 ;
beta( 2 )= 1.7693e+00 ;
beta( 3 )= 1.5588e+02 ;
beta( 4 )= 3.9007e-01 ;
beta( 5 )= -1.6413e-01 ;
beta( 6 )= 2.2921e-01 ;
beta( 7 )= 2.3652e-01 ;
beta( 8 )= 1.4858e-01 ;

v=beta(1) + beta(2)*min(shelf_width,beta(3)).^beta(4).*vmax.^beta(5).*rmax.^beta(6).*cos(phi*pi/180).*r35.^beta(7).*a.^beta(8);
