function v=compute_normal_surge_along_track_shift(shelf_width,phi,a)
% Computes normal surge along-track shift (in km)
% Script automatically generated by fit_along_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)
% a              = dean slope (-)

% R2    = 0.94632
% RMSE  = 3.3413
% MEAN  = 1.8965
% RANGE = -23.4066 - 28.7185

beta( 1 )= 1.8603e+00 ;
beta( 2 )= -1.8650e+00 ;
beta( 3 )= 3.6023e-01 ;
beta( 4 )= -2.4097e-01 ;

v=beta(1) + beta(2)*sin(phi*pi/180).*shelf_width.^beta(3).*a.^beta(4);
