function v=compute_normal_surge_reduction_extent(shelf_width,phi,rmax,r35,a)
% Computes normal surge reduction extent (km)
% Script automatically generated by fit_normal_surge_reduction_extent.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)
% rmax           = rmax (km)
% r35            = r35 (km)
% a              = dean slope (-)

% R2    = 0.87389
% RMSE  = 12.5416
% MEAN  = 71.5041
% RANGE = 16.1713 - 155.2934

beta( 1 )= 9.6795e+00 ;
beta( 2 )= 1.9430e-01 ;
beta( 3 )= 1.2281e+00 ;
beta( 4 )= -4.8648e-01 ;
beta( 5 )= -1.1017e+01 ;
beta( 6 )= 1.9121e-01 ;
beta( 7 )= 5.0099e-02 ;
beta( 8 )= 2.9843e-01 ;

v=beta(1) + beta(2)*shelf_width.^beta(3).*(1+beta(4)*cos((phi-beta(5))*pi/180)).*rmax.^beta(6).*r35.^beta(7).*a.^beta(8);
