function v=compute_normal_surge_land_reduction_factor(vmax,track_angle,a,shelf_width)
% Computes normal surge reduction factor
% Script automatically generated by fit_normal_surge_reduction_factor.m
% Inputs : 
% vmax        = Vmax (km/h)
% r35         = R35 (km)
% track_angle = track angle (deg)
% a           = Dean slope (-)

% R2    = 0.60395
% RMSE  = 0.054487
% MEAN  = 0.71886
% RANGE = 0.53379 - 0.87654

beta( 1 )= 2.0414e-01 ;
beta( 2 )= 2.4481e+02 ;
beta( 3 )= 1.2986e-01 ;
beta( 4 )= 1.2223e+02 ;
beta( 5 )= 1.9864e-01 ;

v = 1.0 - beta(1)*exp(-vmax/beta(2)).*(1+cos(track_angle*pi/180)).*a.^beta(3).*max(shelf_width,beta(4)).^beta(5);
