function stationsV2 = getActiveStationsV2(obj)
%getActiveStationsV2(obj)
%
%     Input:
%   
%     Output:
%       stationsV2 = (stationsV2)

% Build up the argument lists.
values = { ...
   };
names = { ...
   };
types = { ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://opendap.co-ops.nos.noaa.gov/axis/webservices/activestations/wsdl', ...
    'getActiveStationsV2', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    '', ...
    soapMessage);
stationsV2 = parseSoapResponseWithAttributes(response);
