function v=compute_total_surge_b2(rmax,r35,phi,shelf_width,vmax,latitude)
% Computes normal surge along-track shift (in km)
% Script automatically generated by fit_along_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)
% a              = dean slope (-)

% R2    = 0.50822
% RMSE  = 38.6085
% MEAN  = 99.0945
% RANGE = 50.5595 - 259.7656

beta( 1 )= 4.9347e+01 ;
beta( 2 )= 7.1756e-01 ;
beta( 3 )= 1.0129e+00 ;
beta( 4 )= 6.0909e-01 ;
beta( 5 )= 2.5204e-01 ;
beta( 6 )= -4.9710e-01 ;
beta( 7 )= -5.3230e-03 ;

v=beta(1)+beta(2).*rmax.^beta(3).*r35.^beta(4).*(1+cos((phi-180)*pi/180)).*shelf_width.^beta(5).*vmax.^beta(6).*(1+beta(7)*latitude);
