function v=compute_total_surge_b1(rmax,r35,phi,shelf_width)
% Computes normal surge along-track shift (in km)
% Script automatically generated by fit_along_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)
% a              = dean slope (-)

% R2    = 0.64733
% RMSE  = 81.4011
% MEAN  = 193.1266
% RANGE = 69.8002 - 625.0453

beta( 1 )= 1.3484e+02 ;
beta( 2 )= 7.6395e-02 ;
beta( 3 )= 8.1137e-01 ;
beta( 4 )= 3.5470e-01 ;
beta( 5 )= 8.1816e-01 ;

v=beta(1)+beta(2).*rmax.^beta(3).*r35.^beta(4).*(1+cos((max(phi,0)-180)*pi/180)).*shelf_width.^beta(5);
