function v=compute_total_surge_smax(vmax,r35,shelf_width,phi,a,foreward_speed,latitude,phi_spiral,rmax,manning)
% Computes normal surge along-track shift (in km)
% Script automatically generated by fit_along_track_shift.m
% Inputs : 
% shelf_width    = width (km)
% phi            = track angle (deg)
% a              = dean slope (-)

% R2    = 0.95808
% RMSE  = 0.28761
% MEAN  = 2.9277
% RANGE = 0.90171 - 6.5439

beta( 1 )= 1.4740e-03 ;
beta( 2 )= 9.8095e-01 ;
beta( 3 )= 9.7078e-02 ;
beta( 4 )= 2.0206e-02 ;
beta( 5 )= 2.8264e-01 ;
beta( 6 )= 1.5945e-01 ;
beta( 7 )= 4.7985e-02 ;
beta( 8 )= 3.3907e-03 ;
beta( 9 )= 6.9781e-03 ;
beta( 10 )= 1.2822e-03 ;
beta( 11 )= -5.5039e+00 ;
beta( 12 )= 1.0753e+02 ;

v=beta(1)*vmax.^beta(2).*exp(-a/beta(3)).*(1+beta(4)*foreward_speed.*cos(phi*pi/180)).*min(shelf_width,beta(12)).^beta(5).*r35.^beta(6).*(1+beta(7)*sin(phi*pi/180)).*(1+beta(8)*latitude).*(1+beta(9)*phi_spiral).*rmax.^(beta(10)./a).*(1+beta(11)*manning);
