% OpenEarth tidal tools distribution:
%
% Generic frequency-domain filters:
%
%  fft_filter            - High/low pass fourier filter for time series
%  harmanal              - regular harmonic analysis with constant + variable dt
%
% Tidal frequency-domain filters based on <a href="http://www.pac.dfo-mpo.gc.ca/science/oceans/tidal-marees/index-eng.htm">Foreman,'77,'78,'79</a>
%
%  t_tide                - tidal + harmonic analysis with constant + variable dt (external)
%   T_TIDE               - Harmonic analysis of a time series
%   T_PREDIC             - Tidal prediction
%   T_XTIDE              - Tidal predictionusing the harmonics file from XTIDE.
%   tide_iho             - class for storing/importing/exporting IHO tidal components
%
%  UTide                 - (signal processing toolbox needed)
%                          tidal + harmonic analysis with constant + variable dt (external)
%   UT_RECONSTR          - Reconstruct superposed harmonics
%   UT_SOLV              - Execute harmonic tidal analysis.
%   ...                  - and more
%
%  t_tide subsidiaries
%   nc_t_tide            - t_tide with netCDF output
%   nc_t_tide_compare    - visualize comparison of nc_t_tide results
%   t_disp               - displays t_tide table of all 146 t_tide components with various units
%   t_tide_name2freq     - Returns frequencies from the T_TIDE component names
%   t_tide_read          - load ascii 'output' file as generated by t_tide
%
% Time-domain filters:
%
%  godin                 - GODIN low-pass tide filter for time series
%  godin_filter          - GODIN low-pass tide filter for time series
%  thompson1983          - Tidal-killer filter 120i913 by <a href="http://dx.doi.org/10.1175/1520-0485(1983)013%3C1077:LPFTSI%3E2.0.CO;2">Thompson, 1983, JPO.</a>
%  thompsonbrazil        - Tidal-killer filter based on theory <a href="http://dx.doi.org/10.1175/1520-0485(1983)013%3C1077:LPFTSI%3E2.0.CO;2">Thompson, 1983, JPO.</a>
%
% Tidal ellipses:
%
%  ABCD2ELLIPSE          - get tidal ellipse parameters from harmonic amplitudes
%  ABCD2RPRM             - get phasor amplitudes from tidal ellipse parameters
%  ep2ap                 - convert from amplitude & phase to ellipse parameters
%  ap2ap                 - convert ellipse parameters to amplitude & phase 
%  plot_ellipse          - plot tidal ellipses on a map using major, minor, inc and phase
%  plot_tidalellipses    - plot tidal ellipses on a map using major, minor, inc and phase
%
%See also: signal_fun, phys_fun, ddb, matroos, rws_waterbase, cmg
